data_pipeline2:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: kd30072.central-india.azure
      user: JosRaj
      password: Login2SF!
      role: Accountadmin
      database: dbt_db
      warehouse: dbt_wh
      schema: dbt_schema
      threads: 10
      client_session_keep_alive: False
